# <a name="exceptions"></a><span data-ttu-id="e2f6f-101">Eccezioni</span><span class="sxs-lookup"><span data-stu-id="e2f6f-101">Exceptions</span></span>

<span data-ttu-id="e2f6f-102">Le eccezioni nel linguaggio c# forniscono un modo strutturato, uniforme e indipendente dai tipi di gestire a livello di sistema sia a livello di applicazione condizioni di errore.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-102">Exceptions in C# provide a structured, uniform, and type-safe way of handling both system level and application level error conditions.</span></span> <span data-ttu-id="e2f6f-103">Il meccanismo delle eccezioni nel linguaggio c# è molto simile a quella di C++, con alcune importanti differenze:</span><span class="sxs-lookup"><span data-stu-id="e2f6f-103">The exception mechanism in C# is quite similar to that of C++, with a few important differences:</span></span>

*  <span data-ttu-id="e2f6f-104">In c#, tutte le eccezioni devono essere rappresentate da un'istanza di un tipo di classe derivato da `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-104">In C#, all exceptions must be represented by an instance of a class type derived from `System.Exception`.</span></span> <span data-ttu-id="e2f6f-105">In C++, qualsiasi valore di qualsiasi tipo è utilizzabile per rappresentare un'eccezione.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-105">In C++, any value of any type can be used to represent an exception.</span></span>
*  <span data-ttu-id="e2f6f-106">In c#, un blocco finally ([l'istruzione try](statements.md#the-try-statement)) può essere usato per scrivere codice di terminazione che viene eseguito in condizioni normali e condizioni eccezionali.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-106">In C#, a finally block ([The try statement](statements.md#the-try-statement)) can be used to write termination code that executes in both normal execution and exceptional conditions.</span></span> <span data-ttu-id="e2f6f-107">Tale codice è difficile scrivere in C++ senza duplicazione del codice.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-107">Such code is difficult to write in C++ without duplicating code.</span></span>
*  <span data-ttu-id="e2f6f-108">In c#, le eccezioni a livello di sistema, ad esempio overflow, divisione per zero e null dereferenzia ben definite, le classi di eccezioni ed Equilibra delle condizioni di errore a livello di applicazione.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-108">In C#, system-level exceptions such as overflow, divide-by-zero, and null dereferences have well defined exception classes and are on a par with application-level error conditions.</span></span>

## <a name="causes-of-exceptions"></a><span data-ttu-id="e2f6f-109">Cause delle eccezioni</span><span class="sxs-lookup"><span data-stu-id="e2f6f-109">Causes of exceptions</span></span>

<span data-ttu-id="e2f6f-110">Eccezione può essere generata in due modi diversi.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-110">Exception can be thrown in two different ways.</span></span>

*  <span data-ttu-id="e2f6f-111">Oggetto `throw` istruzione ([l'istruzione throw](statements.md#the-throw-statement)) genera un'eccezione immediatamente e in modo incondizionato.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-111">A `throw` statement ([The throw statement](statements.md#the-throw-statement)) throws an exception immediately and unconditionally.</span></span> <span data-ttu-id="e2f6f-112">Controllo non raggiunga mai l'istruzione che segue immediatamente il `throw`.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-112">Control never reaches the statement immediately following the `throw`.</span></span>
*  <span data-ttu-id="e2f6f-113">Alcune condizioni eccezionali che si verificano durante l'elaborazione di istruzioni c# ed espressione generano un'eccezione in alcuni casi quando l'operazione non può essere completata normalmente.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-113">Certain exceptional conditions that arise during the processing of C# statements and expression cause an exception in certain circumstances when the operation cannot be completed normally.</span></span> <span data-ttu-id="e2f6f-114">Ad esempio, un'operazione di divisione integer ([operatore di divisione](expressions.md#division-operator)) genera un `System.DivideByZeroException` se il denominatore è zero.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-114">For example, an integer division operation ([Division operator](expressions.md#division-operator)) throws a `System.DivideByZeroException` if the denominator is zero.</span></span> <span data-ttu-id="e2f6f-115">Visualizzare [classi di eccezioni comuni](exceptions.md#common-exception-classes) per un elenco delle varie eccezioni che possono verificarsi in questo modo.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-115">See [Common Exception Classes](exceptions.md#common-exception-classes) for a list of the various exceptions that can occur in this way.</span></span>

## <a name="the-systemexception-class"></a><span data-ttu-id="e2f6f-116">La classe System. Exception</span><span class="sxs-lookup"><span data-stu-id="e2f6f-116">The System.Exception class</span></span>

<span data-ttu-id="e2f6f-117">Il `System.Exception` classe è il tipo di base di tutte le eccezioni.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-117">The `System.Exception` class is the base type of all exceptions.</span></span> <span data-ttu-id="e2f6f-118">Questa classe ha alcune proprietà importanti che condividono tutte le eccezioni:</span><span class="sxs-lookup"><span data-stu-id="e2f6f-118">This class has a few notable properties that all exceptions share:</span></span>

*  <span data-ttu-id="e2f6f-119">`Message` è una proprietà di sola lettura di tipo `string` contenente una descrizione leggibile del motivo dell'eccezione.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-119">`Message` is a read-only property of type `string` that contains a human-readable description of the reason for the exception.</span></span>
*  <span data-ttu-id="e2f6f-120">`InnerException` è una proprietà di sola lettura di tipo `Exception`.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-120">`InnerException` is a read-only property of type `Exception`.</span></span> <span data-ttu-id="e2f6f-121">Se il valore è diverso da null, fa riferimento all'eccezione che ha causato l'eccezione corrente, vale a dire, è stato generato l'eccezione corrente in un blocco catch gestisce le `InnerException`.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-121">If its value is non-null, it refers to the exception that caused the current exception—that is, the current exception was raised in a catch block handling the `InnerException`.</span></span> <span data-ttu-id="e2f6f-122">In caso contrario, il relativo valore è null, che indica che questa eccezione non è stata causata da un'altra eccezione.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-122">Otherwise, its value is null, indicating that this exception was not caused by another exception.</span></span> <span data-ttu-id="e2f6f-123">Il numero di oggetti eccezione concatenate in questo modo può essere arbitrario.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-123">The number of exception objects chained together in this manner can be arbitrary.</span></span>

<span data-ttu-id="e2f6f-124">Il valore di queste proprietà può essere specificato nelle chiamate al costruttore di istanza per `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-124">The value of these properties can be specified in calls to the instance constructor for `System.Exception`.</span></span>

## <a name="how-exceptions-are-handled"></a><span data-ttu-id="e2f6f-125">Gestione delle eccezioni</span><span class="sxs-lookup"><span data-stu-id="e2f6f-125">How exceptions are handled</span></span>

<span data-ttu-id="e2f6f-126">Le eccezioni vengono gestite da un `try` istruzione ([l'istruzione try](statements.md#the-try-statement)).</span><span class="sxs-lookup"><span data-stu-id="e2f6f-126">Exceptions are handled by a `try` statement ([The try statement](statements.md#the-try-statement)).</span></span>

<span data-ttu-id="e2f6f-127">Quando si verifica un'eccezione, il sistema cerca più vicini `catch` clausola in grado di gestire l'eccezione, come determinato dal tipo di runtime dell'eccezione.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-127">When an exception occurs, the system searches for the nearest `catch` clause that can handle the exception, as determined by the run-time type of the exception.</span></span> <span data-ttu-id="e2f6f-128">In primo luogo, il metodo corrente viene cercato un livello lessicale di inclusione `try` istruzione e le clausole catch associata dell'istruzione try sono considerati nell'ordine.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-128">First, the current method is searched for a lexically enclosing `try` statement, and the associated catch clauses of the try statement are considered in order.</span></span> <span data-ttu-id="e2f6f-129">Se il problema persiste, il metodo che ha chiamato il metodo corrente viene cercato un livello lessicale di inclusione `try` istruzione che include il punto della chiamata al metodo corrente.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-129">If that fails, the method that called the current method is searched for a lexically enclosing `try` statement that encloses the point of the call to the current method.</span></span> <span data-ttu-id="e2f6f-130">Questa ricerca continua fino a quando un `catch` clausola viene trovata in grado di gestire l'eccezione corrente, assegnando una classe di eccezione che è della stessa classe o una classe base, del tipo di eccezione generata in fase di esecuzione.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-130">This search continues until a `catch` clause is found that can handle the current exception, by naming an exception class that is of the same class, or a base class, of the run-time type of the exception being thrown.</span></span> <span data-ttu-id="e2f6f-131">Oggetto `catch` clausola che non denominare una classe di eccezione può gestire tutte le eccezioni.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-131">A `catch` clause that doesn't name an exception class can handle any exception.</span></span>

<span data-ttu-id="e2f6f-132">Una volta trovata una clausola catch corrispondente, il sistema si prepara al trasferimento di controllo per la prima istruzione della clausola catch.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-132">Once a matching catch clause is found, the system prepares to transfer control to the first statement of the catch clause.</span></span> <span data-ttu-id="e2f6f-133">Prima dell'inizio dell'esecuzione della clausola catch, il sistema esegue prima, in ordine, qualsiasi `finally` clausole che erano associate a più istruzioni di prova annidati che da quello che ha generato l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-133">Before execution of the catch clause begins, the system first executes, in order, any `finally` clauses that were associated with try statements more nested that than the one that caught the exception.</span></span>

<span data-ttu-id="e2f6f-134">Se non viene trovata alcuna clausola catch corrispondente, si verifica una delle seguenti operazioni:</span><span class="sxs-lookup"><span data-stu-id="e2f6f-134">If no matching catch clause is found, one of two things occurs:</span></span>

*  <span data-ttu-id="e2f6f-135">Se la ricerca di una clausola catch raggiunge un costruttore statico ([costruttori statici](classes.md#static-constructors)) o un inizializzatore di campo statico, un `System.TypeInitializationException` viene generata in corrispondenza del punto che ha attivato la chiamata del costruttore statico.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-135">If the search for a matching catch clause reaches a static constructor ([Static constructors](classes.md#static-constructors)) or static field initializer, then a `System.TypeInitializationException` is thrown at the point that triggered the invocation of the static constructor.</span></span> <span data-ttu-id="e2f6f-136">L'eccezione interna del `System.TypeInitializationException` contiene l'eccezione che è stata inizialmente generata.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-136">The inner exception of the `System.TypeInitializationException` contains the exception that was originally thrown.</span></span>
*  <span data-ttu-id="e2f6f-137">Se la ricerca delle clausole catch corrispondenti raggiunge il codice che ha avviato il thread, viene terminata l'esecuzione del thread.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-137">If the search for matching catch clauses reaches the code that initially started the thread, then execution of the thread is terminated.</span></span> <span data-ttu-id="e2f6f-138">L'impatto di tale azione è definito dall'implementazione.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-138">The impact of such termination is implementation-defined.</span></span>

<span data-ttu-id="e2f6f-139">Le eccezioni che si verificano durante l'esecuzione del distruttore sono nota particolare merita.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-139">Exceptions that occur during destructor execution are worth special mention.</span></span> <span data-ttu-id="e2f6f-140">Se si verifica un'eccezione durante l'esecuzione del distruttore e tale eccezione non rilevata, l'esecuzione del distruttore viene terminata e viene chiamato il distruttore della classe di base (se presente).</span><span class="sxs-lookup"><span data-stu-id="e2f6f-140">If an exception occurs during destructor execution, and that exception is not caught, then the execution of that destructor is terminated and the destructor of the base class (if any) is called.</span></span> <span data-ttu-id="e2f6f-141">Se non è presente alcuna classe di base (come nel caso del `object` tipo) o se non vi è alcun distruttore della classe base, l'eccezione viene eliminata.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-141">If there is no base class (as in the case of the `object` type) or if there is no base class destructor, then the exception is discarded.</span></span>

## <a name="common-exception-classes"></a><span data-ttu-id="e2f6f-142">Classi di eccezioni comuni</span><span class="sxs-lookup"><span data-stu-id="e2f6f-142">Common Exception Classes</span></span>

<span data-ttu-id="e2f6f-143">Le seguenti eccezioni vengono generate da determinate operazioni in c#.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-143">The following exceptions are thrown by certain C# operations.</span></span>

|                                      |                |
|--------------------------------------|----------------|
| `System.ArithmeticException`         | <span data-ttu-id="e2f6f-144">Classe di base per le eccezioni che si verificano durante operazioni aritmetiche, quali `System.DivideByZeroException` e `System.OverflowException`.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-144">A base class for exceptions that occur during arithmetic operations, such as `System.DivideByZeroException` and `System.OverflowException`.</span></span> | 
| `System.ArrayTypeMismatchException`  | <span data-ttu-id="e2f6f-145">Generata quando un archivio in una matrice non riesce perché il tipo effettivo dell'elemento archiviato è incompatibile con il tipo effettivo della matrice.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-145">Thrown when a store into an array fails because the actual type of the stored element is incompatible with the actual type of the array.</span></span> | 
| `System.DivideByZeroException`       | <span data-ttu-id="e2f6f-146">Generata quando si verifica un tentativo di dividere un valore integrale per zero.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-146">Thrown when an attempt to divide an integral value by zero occurs.</span></span> | 
| `System.IndexOutOfRangeException`    | <span data-ttu-id="e2f6f-147">Generata quando un tentativo di indicizzare una matrice tramite un indice minore di zero o supera i limiti della matrice.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-147">Thrown when an attempt to index an array via an index that is less than zero or outside the bounds of the array.</span></span> | 
| `System.InvalidCastException`        | <span data-ttu-id="e2f6f-148">Generata quando una conversione esplicita da un tipo di base o interfaccia a un tipo derivato non riesce in fase di esecuzione.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-148">Thrown when an explicit conversion from a base type or interface to a derived type fails at run time.</span></span> | 
| `System.NullReferenceException`      | <span data-ttu-id="e2f6f-149">Generata quando un `null` riferimento viene usato in modo che l'oggetto di riferimento obbligatorio.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-149">Thrown when a `null` reference is used in a way that causes the referenced object to be required.</span></span> | 
| `System.OutOfMemoryException`        | <span data-ttu-id="e2f6f-150">Generata quando si tenta di allocare la memoria (tramite `new`) ha esito negativo.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-150">Thrown when an attempt to allocate memory (via `new`) fails.</span></span> | 
| `System.OverflowException`           | <span data-ttu-id="e2f6f-151">Generata quando si verifica un overflow di un'operazione aritmetica in un contesto `checked`.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-151">Thrown when an arithmetic operation in a `checked` context overflows.</span></span> | 
| `System.StackOverflowException`      | <span data-ttu-id="e2f6f-152">Generata quando viene esaurito lo stack di esecuzione in un numero eccessivo di chiamate a metodi in sospeso; in genere indicativi di ricorsione troppo profonda o illimitata.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-152">Thrown when the execution stack is exhausted by having too many pending method calls; typically indicative of very deep or unbounded recursion.</span></span> | 
| `System.TypeInitializationException` | <span data-ttu-id="e2f6f-153">Generata quando un costruttore statico genera un'eccezione e nessun `catch` clausole esiste per intercettarla.</span><span class="sxs-lookup"><span data-stu-id="e2f6f-153">Thrown when a static constructor throws an exception, and no `catch` clauses exists to catch it.</span></span> | 
